version: 1.0.{build}
branches:
  except:
  - test-travis
image: Visual Studio 2017
clone_depth: 8
clone_folder: C:\w\
build:
  verbosity: detailed
environment:
  BINTRAY_APIKEY:
    secure: jT/tMOSpo6fjjKZosT3WwhN0wdsdLPtzx1inUSqidw2RqU03ibMR936e4ZYiTabT
  GPG_PASSPHRASE:
    secure: t0zZqLgvaePWqUGn/dLMQ50M3YkMTktXSWglL1dyaEHKTOuXYiNe070dNlJEAoi1
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=
  CODESIGN_GPG_PASS:
    secure: pVgDvVAXHLE+EMsDNKa+VY3kz/w1DLWpIAAiaEoahY7tRx7QpMzlMDND07CN1xN+
  CODESIGN_KEY_PASS:
    secure: WpvrivnhUx4RI4Y02hRjj6T+7IGQADpdU5nIQh1oW8jrUaujbmUmGCxG6vANeasz
build_script:
  - set PATH=C:\Python27-x64;C:\msys64\usr\bin;%SystemRoot%\system32
  - pacman --noconfirm --noprogressbar -S --needed mc
  - pacman --noconfirm --noprogressbar -S -yu -u
  - pacman --noconfirm --noprogressbar -S -yu -u
  - pacman --noconfirm --noprogressbar -S --needed p7zip mingw-w64-{i686,x86_64}-{clang,jq,osslsigncode}
  - set CURL_CC=clang
  - set CURL_AR=llvm-ar
  - set CURL_RANLIB=llvm-ranlib
  - set LIBSSH2_CC=%CURL_CC%
  - set LIBSSH2_AR=%CURL_AR%
  - set LIBSSH2_RANLIB=%CURL_RANLIB%
  - sh -c ./_build.sh
artifacts:
  - path: '*-*-mingw.*'
    name: master
  - path: '*-*-mingw-libressl.*'
    name: master-libressl
  - path: 'all-mingw.*'
    name: all
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
