version: 1.0.{build}
branches:
  except:
  - dev-travis
  - test-travis
image: Visual Studio 2017
clone_depth: 8
clone_folder: C:\w\
build:
  verbosity: detailed
environment:
  BINTRAY_APIKEY:
    secure: jT/tMOSpo6fjjKZosT3WwhN0wdsdLPtzx1inUSqidw2RqU03ibMR936e4ZYiTabT
  GPG_PASSPHRASE:
    secure: t0zZqLgvaePWqUGn/dLMQ50M3YkMTktXSWglL1dyaEHKTOuXYiNe070dNlJEAoi1
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=
  CODESIGN_GPG_PASS:
    secure: pVgDvVAXHLE+EMsDNKa+VY3kz/w1DLWpIAAiaEoahY7tRx7QpMzlMDND07CN1xN+
  CODESIGN_KEY_PASS:
    secure: WpvrivnhUx4RI4Y02hRjj6T+7IGQADpdU5nIQh1oW8jrUaujbmUmGCxG6vANeasz
  CC: mingw-clang
build_script:
  - set PATH=C:\Python27-x64;C:\msys64\usr\bin;%SystemRoot%\system32
  - pacman --noconfirm --ask 20 --noprogressbar -S --needed mc
  - pacman --noconfirm --ask 20 --noprogressbar -S -yu -u
  - pacman --noconfirm --ask 20 --noprogressbar -S -yu -u
  - if "%CC%" == "mingw-clang" set _OPTPKG=mingw-w64-{i686,x86_64}-clang
  - pacman --noconfirm --ask 20 --noprogressbar -S --needed p7zip mingw-w64-{i686,x86_64}-{cmake,jq,osslsigncode} %_OPTPKG%
  - sh -c ./_build.sh
artifacts:
  - path: '*-*-mingw*.*'
    name: master
  - path: 'all-mingw*.*'
    name: all
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
