---
# yamllint disable rule:line-length
version: 1.0.{build}
branches:
  except:
    - dev-travis
    - test-travis
image:
  - Ubuntu
  - Visual Studio 2017
services:
  - docker
clone_depth: 8
build:
  verbosity: detailed
environment:
  BINTRAY_APIKEY:
    secure: jT/tMOSpo6fjjKZosT3WwhN0wdsdLPtzx1inUSqidw2RqU03ibMR936e4ZYiTabT
  GPG_PASSPHRASE:
    secure: t0zZqLgvaePWqUGn/dLMQ50M3YkMTktXSWglL1dyaEHKTOuXYiNe070dNlJEAoi1
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=
  CODESIGN_GPG_PASS:
    secure: pVgDvVAXHLE+EMsDNKa+VY3kz/w1DLWpIAAiaEoahY7tRx7QpMzlMDND07CN1xN+
  CODESIGN_KEY_PASS:
    secure: WpvrivnhUx4RI4Y02hRjj6T+7IGQADpdU5nIQh1oW8jrUaujbmUmGCxG6vANeasz
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  CC: mingw-clang
build_script:
  - cmd: set PATH=C:\msys64\usr\bin;%SystemRoot%\system32
  - cmd: pacman --noconfirm --ask 20 --noprogressbar -S --needed mc
  - cmd: pacman --noconfirm --ask 20 --noprogressbar -S -yu -u
  - cmd: pacman --noconfirm --ask 20 --noprogressbar -S -yu -u
  - cmd: if "%CC%" == "mingw-clang" set _OPTPKG=mingw-w64-{i686,x86_64}-clang
  - cmd: pacman --noconfirm --ask 20 --noprogressbar -S --needed zip mingw-w64-{i686,x86_64}-{cmake,jq,osslsigncode,python3-pip} %_OPTPKG%
  - cmd: sh -c ./_build.sh
  - sh: dpkg --add-architecture i386
  - sh: apt-get -qq update
  - sh: apt-get -qq install curl git make python3-pip binutils-mingw-w64 gcc-mingw-w64 clang autoconf automake libtool cmake zip time jq dos2unix osslsigncode wine-stable wine64 wine32
  - sh: ./_build.sh
artifacts:
  - path: '*-*-mingw*.*'
    name: master
  - path: 'all-mingw*.*'
    name: all
# init:
#   - sh: curl -sfL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
