---
# https://docs.gitlab.com/ce/ci/yaml/README.html

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "8"

build:
  image: debian:testing
  variables:
    CC: mingw-clang
  script:
    - ./_ci-linux-debian.sh
  artifacts:
    expire_in: 13 weeks
    paths:
      - "*-*-mingw*.*"
  only:
    - master
    - dev-gitlab
    - test-gitlab
