---
# yamllint disable rule:line-length
branches:
  only:
    - master
    - dev-travis
    - test-travis
notifications:
  email: false
git:
  depth: 8
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: edge
      compiler: mingw-clang
      services: [docker]
      # https://hub.docker.com/_/debian/
      env: DOCKER_IMAGE=debian:unstable
    # TODO: remove after migrating to Debian builds
    - os: osx
      # https://docs.travis-ci.com/user/reference/osx/#using-os-x
      osx_image: &mac-image xcode9.4
      compiler: mingw-clang
      env: CPU=64
    # TODO: remove after migrating to Debian builds
    - os: osx
      osx_image: *mac-image
      compiler: mingw-clang
      env: CPU=32

script:
  - |
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "$(pwd):$(pwd)" -w "$(pwd)" \
        --env-file <(env | grep -E '^(TRAVIS_|BINTRAY_|GPG_|VIRUSTOTAL_|CODESIGN_|CC)') \
        "${DOCKER_IMAGE}" \
        sh -c ./_ci_linux_debian.sh
    elif [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      ./_ci_mac_homebrew.sh
    fi
