# https://lint.travis-ci.org/
branches:
  only:
  - master
  - test-travis
  - dev-travis
notifications:
  email: false
git:
  depth: 8
language: c

addons:
  apt:
    packages: [ binutils-mingw-w64, gcc-mingw-w64, cmake, p7zip-full, gnupg-curl, dos2unix, realpath ]

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: edge
      compiler: mingw-clang
      services: [ docker ]
      # https://hub.docker.com/_/ubuntu/
      env: DOCKER_IMAGE=ubuntu:rolling
    - os: osx
      osx_image: &mac-image xcode9.1
      compiler: mingw-clang
      env: CPU=64
    - os: osx
      osx_image: *mac-image
      compiler: mingw-clang
      env: CPU=32

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      [ "${CC}" = 'mingw-clang' ] && _clang='llvm'
      export HOMEBREW_NO_AUTO_UPDATE=1
      time travis_retry brew update > /dev/null
      time travis_retry brew install p7zip mingw-w64 ${_clang} jq osslsigncode dos2unix gpg gnu-sed
      time travis_retry brew install --force-bottle --build-bottle wine
      time wineboot --init
    elif [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "${PWD}:${PWD}" -w "${PWD}" \
        --env-file <(env | grep -E '^(TRAVIS_|BINTRAY_|GPG_|VIRUSTOTAL_|CODESIGN_|CC)') \
        "${DOCKER_IMAGE}" sh -c '
        cat /etc/*-release
        ulimit -a
        df -h
        [ "${CC}" = 'mingw-clang' ] && _clang='clang'
        [ "${TRAVIS_BRANCH#*dev*}" != "${TRAVIS_BRANCH}" ] && _clang="${_clang} autoconf automake libtool"
        dpkg --add-architecture i386
        apt-get -qq update
        apt-get -qq install \
          curl git make python python-pip \
          binutils-mingw-w64 gcc-mingw-w64 ${_clang} cmake \
          p7zip-full time jq dos2unix realpath osslsigncode wine-stable wine64 wine32
        ./_build.sh'
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      ./_build.sh
    fi
